### PR TITLE
Fx68k

### PR DESCRIPTION
**Pull request by MarcelKilgus**
I've been side-developing this alternative QL core for over two years now and it seems pretty stable at this point. User feedback is positive too (e.g. https://misterfpga.org/viewtopic.php?f=14&t=1223). Among other things it adds:
- support for QL-SD at all CPU speeds
- QL-SD can mount images on MiSTer SD card
- an almost cycle perfect QL speed (thanks to fx68k core)
- a CPU accelerator card/boot ROM similar to the original "GoldCard" and "SuperGoldCard" hardware extensions to supports loading the advanced operating system SMSQ/E.

Please check the readme.md for details.

### CODE REVIEW

**Comment by sorgelig** [comment]
Thanks for big improvements! It's good there is an active development for almost abandoned core.

**Comment by sorgelig** [comment]
@MarcelKilgus 
I've tweaked sdram module to use register in input buffer. It makes good SDRAM_DQ timings and stable across builds. Please check if the core logic haven't been broken. It adds one cycle for read. If it's critical then can try to do some trick, but if it's OK now, then better keep as it is. It also fixes warnings about unable to put dout into i/o port.

there are other kind of critical issues in the core. 
see blue warnings in Quartus compilation log:
```
Warning (332060): Node: emu:emu|zx8302:zx8302|ipc:ipc|keyboard:keyboard|clk_delay_cnt[12] was determined to be a clock but was found without an associated clock assignment.
Warning (332060): Node: emu:emu|zx8301:zx8301|vs was determined to be a clock but was found without an associated clock assignment.
Warning (332060): Node: emu:emu|qimi:qimi|irq was determined to be a clock but was found without an associated clock assignment.
Warning (332060): Node: emu:emu|zx8302:zx8302|irq_mask[0] was determined to be a clock but was found without an associated clock assignment.
Warning (332060): Node: emu:emu|zx8302:zx8302|mctrl[1] was determined to be a clock but was found without an associated clock assignment.
```
using signals as clocks is a bad idea. It may make core unstable in some cases.

**Comment by sorgelig** [comment]
I can fix these issues if you want. Then you can check how tweaks are compatible with original logic.

**Comment by MarcelKilgus** [comment]
@sorgelig Sure! I'm a software developer by trade and not very experienced with FPGAs, so I'd gladly accept any expert advice :-)

**Comment by sorgelig** [comment]
i've pushed my tweaks. Check if it's ok for core logic.

**Comment by MarcelKilgus** [comment]
Works fine so far. SDRAM change doesn't seem to have any impact and the others ones still work, too (they were even from original MiST source, so at least not my fault :-P).  Thank you!

Fun fact: while testing the keyboard I noticed again that it loses keys when typing too fast, especially when invoking Shift. Looked at the code again and still couldn't explain it. But then had an idea and as it turns out this is most likely a problem in the original QL keyboard controller firmware that runs in the 8049, it's just that on today's keyboards one can type much faster than on the QL...

There was an alternative 3rd party co-processor called Hermes back in the day that fixes this. I will contact some people to see if I can acquire its firmware or if it's possible to read it out of the 8749 chip, the problem is actually pretty annoying on MiSTer.

**Comment by sorgelig** [comment]
Or may be can patch existing FW? Since you are familiar with QL, then probably you have idea how to fix FW. I think IDAPro can be used to disassemble 8049.
I don't know how much 8049 FW is customizable. If it's hardcoded like PC/AT keyboard MCU, then the whole MCU can be scrapped and functionally emulated in pure HDL.

**Comment by sorgelig** [comment]
did you see this article?
http://qemulator.blogspot.com/2020/05/dumping-intel-8049-roms.html

**Comment by MarcelKilgus** [comment]
I have an IDA Pro license but unfortunately the MCS-48 architecture is not supported. On the plus side there is already a marginally commented disassembly, though not in a format that can be accepted by an assembler and the MCS-48 language is generally very hard to read. But I have already contacted the original vendor of the Hermes chip, we'll see if that turns out anything (regarding the article, yes, the first comment there is mine ;) Unfortunately unlike the 8049 the 8749 which was used for Hermes can probably not be read out easily according to the datasheet).

The IPC serves serial ports, keyboard and what counts as "sound" on the QL. Certainly doable in HDL, especially as the serial ports can be left out, but I hope for an easier way. I'll see what I can do.

More importantly, I tried your release, it works fine for me but unfortunately I already got one user report that it doesn't work for him (while my core did). The Minerva OS reports single bit RAM errors on boot (with CPU speed != QL), interestingly both at the end of a row ($3F4 and $3FC). I cannot reproduce it with my v1 SDRAM board. Do you maybe have any idea?
20210306_175457-screen
20210306_171810-screen

**Comment by sorgelig** [comment]
I think it's faulty SDRAM unless there is some issues in SDRAM controller. Combinatonal logic used for SDRAM_DQ read before had higher times which could help for that user, but you need to know that combinatonal logic chain is not stable between builds. You will get completely different timings in different builds so it may work in one build and fail in other.
But since it happens for him only when  CPU speed != QL then may be there is some other factor besides the SDRAM affecting it. I've saw quite tricky way to signal ram dtack 2 cycles in advance of real data. May be move it to at least 1 cycle in advance?

**Comment by MarcelKilgus** [comment]
Moving dtack didn't help, I'll try to increase the tRP wait-state in STATE_READ_DATA_2 again next. But one question regarding your changes, "dout" is already defined as "output reg", was there really combinatory logic in this case?

**Comment by MarcelKilgus** [comment]
By the way, I managed to dump a Hermes chip (turns out the D8749 is as easy to dump as the 8049 using the mentioned Arduino solution after all). Improved the keyboard by **a lot**. I'll see if I can secure the rights to simply include it.

**Comment by sorgelig** [comment]
we can use it as loadable with original FW preloaded. 
user can place boot1.rom if want a custom FW.

**Comment by sorgelig** [comment]
> I'll try to increase the tRP wait-state in STATE_READ_DATA_2 again next.

i suggest to move dtack<=1 for reading to one step later.



> "dout" is already defined as "output reg", was there really combinatory logic in this case?

it was not about dout. SDRAM_DQ must be read to only ONE register. In your original code SDRAM_DQ was reading into 2 different registers dout and cache. 2 registers cannot be placed in IOBUF, so if you want to use register in pin's input buffer then you have to use only one register. Otherwise buffer won't be used and quartus will place registers anywhere with long paths and therefore delays.

**Comment by MarcelKilgus** [comment]
> i suggest to move dtack<=1 for reading to one step later.

I already tried that. Only thing that actually helped was reinstating the "assign SDRAM_nCS  = sd_cmd[3];" line to toggle chip select. I just don't understand yet why that works.

Also one other question if I may: the SDRAM clock used to be phase shifted until commit 17acf4a. I've seen those shifts on a few  different projects, isn't it needed on MiSTer?

> it was not about dout. SDRAM_DQ must be read to only ONE register. In your original code SDRAM_DQ was reading into 2 different registers dout and cache. 2 registers cannot be placed in IOBUF, so if you want to use register in pin's input buffer then you have to use only one register. Otherwise buffer won't be used and quartus will place registers anywhere with long paths and therefore delays.

Aaaah, I see, thanks for the explanation, much appreciated!

**Comment by sorgelig** [comment]
Clock shift is old way to clock SDRAM. Clock shift doesn't work well as it's not constrained. Phase shift is constrained only on PLL output. It's not constrained when it's on output pin. Constrains calculated against clock, but shifted clock is clock itself and therefore it's like free running on whatever phase it comes to a pin. altddio uses output buffer register which is well constrained against clock used on whole SDRAM module, so you get the same delays between builds (unlike shifted clock).

> Only thing that actually helped was reinstating the "assign SDRAM_nCS = sd_cmd[3];" line to toggle chip select. I just don't understand yet why that works.

Ok, then keep it that way. It's acceptable even for 128MB module. There is a chance that second chip may drive DQ when nCS=1 as it uses inverted nCS signal, but chances should be low.

**Pull request merged**
